apiVersion: v1
kind: ConfigMap
metadata:
  name: fraud-detection-config
data:
  application-prod.yml: |
    spring:
      application:
        name: fraud-detection-service
      security:
        user:
          name: {{ .Values.secutity.username }}
          password: {{ .Values.secutity.password }}
          roles: ADMIN
    server:
      port: 8081
    logging:
      level:
        root: INFO
        com.example.frauddetection: DEBUG

    management:
      endpoints:
        enabled-by-default: true
        web:
          exposure:
            include: "*"
      endpoint:
        shutdown:
          enabled: true
    rule:
      debug: false
    aws:
      accessKey: {{ .Values.aws.accessKey }}
      secretKey: {{ .Values.aws.secretKey }}
      region: {{ .Values.aws.region }}
    fraud-detection:
      pool-size: {{ .Values.fraudDetectionService.poolSize }}
      batch-size: {{ .Values.fraudDetectionService.batchSize }}
      wait-time-seconds: {{ .Values.fraudDetectionService.waitTimeSeconds }}
      notify-queue: {{ .Values.aws.notifyQueueName }}
      transaction-queue: {{ .Values.aws.transactionQueueName }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: trans-generator-config
data:
  application-prod.yml: |
    spring:
      application:
        name: trans-generator
    server:
      port: 8080
    logging:
      level:
        root: INFO
        com.example.frauddetection: DEBUG

    management:
      endpoints:
        web:
          exposure:
            include: "*"
    aws:
      accessKey: {{ .Values.aws.accessKey }}
      secretKey: {{ .Values.aws.secretKey }}
      region: {{ .Values.aws.region }}
    trans-generator:
      enabled: true
    queue:
      name: {{ .Values.aws.transactionQueueName }}