{{- if .Values.fraudDetectionService.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: fraud-detection-service
spec:
  minReplicas: {{ .Values.fraudDetectionService.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.fraudDetectionService.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.fraudDetectionService.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.fraudDetectionService.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.fraudDetectionService.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.fraudDetectionService.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fraud-detection-service
{{- end }}


